### ISSUE TITLE
HTTP_RANGE / Accept-Range Support

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/download#11]
Um aus dem Medienpool sauber zu streamen, während die Ausgabe durch Redaxo läuft (zB für Tracking oder das Handling der Rechte oder Dateinamen), braucht es insbesondere bei Podcasts einen HTTP Range support. 

In Processwire gibt es hier einen Support, der in dieses Addon evtl auch passen würde:

https://github.com/horst-n/LocalAudioFiles/blob/master/site-default/templates/local-audio-files_stream.php#L250-L357

**Comment by skerbis** [comment]
Wurde bereits im media Manager realisiert
