### ISSUE TITLE
Download-Berechtigung begrenzen

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/download#2]
Bspw. soll die Datei nicht downloadbar sein, wenn nicht eine bestimmte Bedingung aktiv ist. (Auch der Zugriff auf den /Media/ Ordner muss dann gesperrt sein.

Evtl. Anbindung an Community-Addon

**Comment by hirbod** [comment]
Man musste mal Brainstormen, wie man das ganz optimal umsetzen kann. Bin für jede Idee/Code-Beitrag offen.

**Comment by AWqxKAWERbXo** [comment]
* Globale Einstellung (am Addon), die ein Whitelisting oder Blacklisting an Kategorien ermöglicht.
* Globale Einstellung (am Addon), die YCom-Gruppen ermöglicht
* Meta-Feld an einer Medienpool-Datei, das eine Beschränkung setzt oder aufhebt.
* EP, in dem man zusätzlich eigene Regeln definieren kann (bspw. nur bestimmte YCom-User/Gruppen, nur bestimmte Session-Cookies, etc.)

**Comment by skerbis** [comment]
Scheint wohl gerade was zu entstehen. https://github.com/yakamara/redaxo_ycom/issues/97

**Comment by AWqxKAWERbXo** [comment]
Ich halte https://www.redaxo.org/doku/master/responses#sendfile hierfür zielführender, es gibt auch einen Media Manager Effekt für Downloads mittlerweile. Das Addon ist für mich obsolet.
